# -*- coding: utf-8 -*-
"""drill-built-in-function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ECV9p9Q7QBKSACF7EJq9m7Vf8C5dm5Oa

# Drill : built-in functions
Use the native python functions to do these exercises.

### 1. Create a variable `count_alpha` that contains the number of characters contained in the string `"Hello world!"`.
"""
text="Hello world!"
count_aplha=len(text)
print(count_aplha)


"""### 2. Create a variable `count_float` and cast the variable `count_alpha` to float."""

count_float=float(count_aplha)
print(count_float)

"""### 3. Round the variable `pi` value to 2 decimal places (0.01) and save it in a variable `round_pi`. You can get `pi` from the `math` library."""
import math
ma = math.pi
round_pi = round(ma, 2)
print(round_pi)


"""### 4. Create a variable `reversed_text` which contains the character string `"Hello world!"` backwards.
The result must be a `list` object.
"""
reversed_text=list(reversed("Hello world!"))
print(reversed_text)


"""### 5. Create a variable `age`  and ask the user to enter his age. Then display it and display its type."""
age=input("Quel votre age ? : ")
print(age)
print(type(age))

"""### 6. Create a variable `sorted_num` that contains the sorted `num` list.

"""

num = [2, 8, 1, 4, 6, 3, 7]
sorted_num=sorted(num)
print(sorted_num)
"""### 7. Create a variable `sum_of_list` which contains the sum of all the elements in the list `num`."""

import numpy as np
num1 = [2, 8, 1, 4, 6, 3, 7]
sum_of_list=np.sum(num1)
print(sum_of_list)
"""### 8. Create a variable `min_value` that contains a minimum value of list `num`."""

num2 = [2, 8, 1, 4, 6, 3, 7]
min_value=np.min(num2)
print(min_value)
"""### 9. Create a variable `max_value` that contains the maximum value of list `num`."""

num3 = [2, 8, 1, 4, 6, 3, 7]
max_value=np.max(num3)
print(max_value)
"""### 10. Find a function that will interpret the string of the variable `calc`
Save the result in a variable named `string_interpret`.
"""

calc = "1 + 2"
string_interpret=eval(calc)
print(string_interpret)

"""## Testing

The following piece of code is to test that you have correctly done the above exercises.
If it fails, it means that some of your code is not correct. Read the error messages of each test carefully.

If the syntax of the code below is confusing (`class`,`self`, etc...), don't worry, you will see it soon. The only thing you should know is that the method `assertEqual` checks if the right argument matches the left one, e.g. for `assertEqual(count_alpha, 12)` it checks that `count_alpha` is equal to 12.

Please don't modify the code, you just have to execute it.
"""

import unittest


class TestNotebook(unittest.TestCase):
    def test_count_alpha(self):
        self.assertEqual(count_alpha, 12)

    def test_count_float(self):
        self.assertEqual(type(count_float), float)

    def test_pi(self):
        self.assertEqual(3.14, round_pi)

    def test_reversed(self):
        self.assertEqual(
            reversed_text, ["!", "d", "l", "r", "o", "w", " ", "o", "l", "l", "e", "H"]
        )

    def test_age(self):
        self.assertEqual(type(age), str)

    def test_sorted(self):
        self.assertEqual(sorted_num, [1, 2, 3, 4, 6, 7, 8])

    def test_sum(self):
        self.assertEqual(sum_of_list, 31)

    def test_min(self):
        self.assertEqual(min_value, 1)

    def test_max(self):
        self.assertEqual(max_value, 8)

    def test_interpret(self):
        self.assertEqual(string_interpret, 3)


unittest.main(argv=[""], verbosity=2, exit=False)

"""## [Next one](../6.tuples-dictionaries/tuples-and-dictionaries.ipynb)"""