# -*- coding: utf-8 -*-
"""drill-conditions-operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mB_nsma-tzPaElkq9YMgZz-luKoYcX4T

# Drill : Basics python syntax

In some of these exercises, you will have to use methods that you have not seen yet. In this case, search on google for an example of use. Take the right habits to avoid being blocked

Run all cells before starting the tests.

**1. Create a variable `age` that contains value 32**
"""
# age=32


"""**2. Add 10 to variable `age`**"""

# age = age + 10

"""**3. Create a variable `divAge` and assign it the value of the age divided by 7**  
- ❗ Be careful, it must be an integer.
"""
# divAge=int(age/7)


"""**4. Create a variable `text_div` that contains the character string "42 divided by 7 equals 6".**  
- You must use the `age` and `div_age` variables
"""
# text_div="42 divided by 7 equals 6"


"""**5. Create a variable `rest_div` that contains the rest of the variable `age` divided by 7**"""

# rest_div=age%7

"""**6. Create a variable `exp_div` that contains the value of `rest_div` to the 3rd power**"""
# exp_div=rest_div**3


"""**7. Write a program that enters an integer and then displays the value entered and its type.**"""

# x=7
# print(x)
# print(type(x))

"""**8. Use variables to represent the price of materials.**  
- 2 bottles of milk at €0.45 each
- 3 bottles of raw cider at €3.85 each
- 1 bag of flour at 0.9 €
- 1 packet of butter at €0.77
- 1 jar of nutella at €1.87  

**Calculate the sum of all items and store it in a `order_price` variable**
"""
# bot=2*0.45
# botplus=3*3.85
# bag=0.9
# pack=0.77
# jar=1.87
# order_price=bot+botplus+bag+pack+jar
# print(order_price)
"""**Create a variable `allowance_money` which has a value of 20 and then create an algorithm that calculates the available money 
by subtracting the price of the order.**

If there is enough money, record the following sentence in the variable `message` and subtract the expense from `allowance_money` :
- message = "You have spent" + `order_price` + "you have left" + `allowance_money`

If there is not enough money, record the following sentence in the `message` variable:
- message= "Sorry you're missing *amount_missing* euros"

If there is 0 left, record the following sentence in the `message` variable:
- message = "You are broke!"

"""
# allowance_money=20-order_price
# if allowance_money > 0:
#     message = f"You have spent {order_price} you have left {allowance_money}"
# elif allowance_money < 0:
#     message = f"Sorry you're missing {allowance_money} euros"
# else:
#     message = "You are broke!"
# print(message)

"""**9. Write a program that asks you to enter 2 values and displays the smallest of the 2 values**"""

# num1=int(input("Give me a number : "))
# num2=int(input("Give me a number : "))
# if num1 < num2:
#     message=f"{num1} est le plus petit des deux"
# else:
#     message=f"{num2} est le plus petit des deux"
# print(message)

"""**10. Write a script that asks you to enter 2 strings and displays the largest of the 2 strings (the one with the most characters).**"""
# str1=input("Give me a string : ")
# str2=input("Give me a string : ")
# if str1 < str2:
#     message=f"{str2} est le plus grand des deux"
# else:
#     message=f"{str1} est le plus grand des deux"
# print(message)


"""**11. Write a script that converts euros into dollars.**
- The program will start by asking the user to indicate with a character 'E' or '$' depending on the currency of the amount they are entering.
- Then the program will ask you to enter the amount and display the conversion."""
# exchange = input("Dollar($) ou euro(E) : ")
# price = float(input("Donne moi un prix : "))
# if exchange == '$':
#     print(price*0.91)
# else:
#     print(price/0.91)
"""**12. Check if the variable `name` is in the `students_turing` list. (Without making a loop)**
* If the name is in the list, display "You are at the turing's".
* Otherwise display: "You are not part of the turing's"
"""
# studentsTuring = ["Redouane", "Justine", "Ruben", "Edouard"]
# name = "Julie"

# if name in studentsTuring:
#     print("You are at the turing's.")
# else:
#     print("You are not part of the turing's.")

"""**13. Calculate the volume of a sphere using the formula *(4π/3) x R³*. The radius is 10.**  
- Save the result in a "volume" variable.

"""
# import math
# pi= math.pi
# volume = ((4*pi)/3)*(10**3)
# print(volume)

